* the admin should be able to update the products 
** User Story: As an admin I can save a new Product on the server
*** Acceptance Stories
**** 1:
    Scenario: Some client goes to admin page
    Given: some client has access to the admin new product page
    When: he clicks the save new product
    Then: he must not be able to save the new product at all
**** 2:
    Scenario: Some client logs in and accesses the admin page
    Given:  client has access to the admin new product page
    And: he is logged in
    And: he is not admin 
    When: he clicks the save new product
    Then: he must not be able to save the new product at all
**** 3:
    Scenario: an admin A goes to admin page
    Given: An admin A logs in 
    And: he opens the admin section
    When: he clicks the save new product
    Then: he should be able to save the new product
**** 4:
    Scenario: an admin A goes to admin page
    Given: An admin A logs in 
    And: he opens the admin section
    When: he clicks edit product page
    Then: he should be able to see the edit product page
**** 5:
    Scenario: an admin A goes to admin page
    Given: An admin A logs in 
    And: he downloads the products list from the server
    When: he clicks the delete button on a product
    Then: he should be able to delete that products
**** tasks
***** task1: create a products menu page which will show a menu for this:
            1. new product
            2. edit existing products
      for that a route in the 'app' is to be created.
***** task2: create a facility to add a new product on the server side
***** task3: creaet client side angularjs codes for saving a new product
***** task4: create cleint side angularjs code for retrieving a list of the products on the server
***** task5: create a directive for product element in the products list. this element will have 'edit' and 'delete' button.
***** task6: code angularjs on client side to delete a particular product.
***** task7: code python on server side to delete a desired product.
